project:
  type: book
  output-dir: _book

book:
  title: "Tidy design principles"
  reader-mode: true

  page-footer:
    left: |
      Tidy design principles was written by Hadley Wickham
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  site-url: https://design.tidyverse.org
  repo-url: https://github.com/tidyverse/design
  repo-branch: main
  repo-actions: [edit, issue]
  
  chapters:
    - index.qmd
    - unifying.qmd
    
    - part: Implementation
      chapters:
      - names.qmd
      - call-data-details.qmd
      - function-names.qmd
        
    - part: Scannable specs
      chapters:
      - inputs-explicit.qmd
      - important-args-first.qmd
      - required-no-defaults.qmd
      - dots-after-required.qmd
      - defaults-short-and-sweet.qmd
      - enumerate-options.qmd
      - argument-clutter.qmd
      - independent-meaning.qmd
    
    - part: explicit-strategies.qmd
      chapters:
      - boolean-strategies.qmd
      - strategy-objects.qmd
      - strategy-functions.qmd
      - cs-rep.qmd
      - implicit-strategies.qmd
      - cs-rvest.qmd
      - identity-strategy.qmd

    - part: Function arguments
      chapters: 
      - def-magical.qmd
      - def-inform.qmd
      - def-user.qmd
      - dots-data.qmd
      - dots-prefix.qmd
      - dots-inspect.qmd
      - cs-mapply-pmap.qmd
      - cs-setNames.qmd
      
    - part: Outputs
      chapters: 
      - out-multi.qmd
      - out-type-stability.qmd
      - out-vectorisation.qmd
      - out-invisible.qmd

    - part: Evolution
      chapters: 
      - changes-multivers.qmd
    
    - part: Side effects
      chapters: 
      - side-effects.qmd
      - spooky-action.qmd

    - part: Errors
      chapters: 
      - err-call.qmd
      - err-constructor.qmd
    
  appendices:
    - glossary.qmd

format:
  html:
    theme:
    - cosmo
    - r4ds.scss
    code-link: true

    number-sections: false
    author-meta: "Hadley Wickham"
    include-in-header: "plausible.html"
    callout-appearance: simple

editor: visual

